---
title: "Welcome"
author: "Latest update - `r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: yeti
  pdf_document:
    toc: yes
---

<style type="text/css">
body{
  font-size: 10pt;
}
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
div.orange { background-color:#ffa366; border-radius: 5px; padding: 20px;}
div.yellow { background-color:#09bb9f; color: white; border-radius: 5px; padding: 20px;}
div.grey { background-color:#ebebeb; color: white; border-radius: 5px; padding: 20px;}

</style>

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>

<!-- setwd('/Users/joachimwaterschoot/Library/CloudStorage/OneDrive-UGent/watjoa.github.io') -->

> "'I do not believe elephants exist at all,' declared the sixth blind man. <br>
'I think we are the victims of a cruel joke.'" 

# Recommended <i class="fa fa-exclamation" aria-hidden="true"></i>
***

## Papers

<div class = "row">
<div class = "col-md-8">
Working with single-item scales in social sciences
</div>
<div class = "col-md-4">
[Allen et al., 2022 <i class="fa fa-file-pdf-o" aria-hidden="true"></i>](https://psycnet.apa.org/record/2022-29445-001)
</div>
</div>

<div class = "row">
<div class = "col-md-8">
How to handle outliers in social sciences
</div>
<div class = "col-md-4">
[Leys et al., 2019 <i class="fa fa-file-pdf-o" aria-hidden="true"></i>](https://doi.org/10.5334/irsp.289)
</div>
</div>

## Websites

<div class = "row">
<div class = "col-md-8">
Research Methods in R
</div>
<div class = "col-md-4">
[Andy Wills <i class="fa fa-file-pdf-o" aria-hidden="true"></i>](http://www.andywills.info/rminr/)
</div>
</div>



